### ISSUE TITLE
Show `Connect to the network` screen only on first time app start

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Account-Manager-Mobile#14]
**Bug Description**
Currently, this `Connect to the network` screen opens everyone time a user opens the app. 

**Steps to Reproduce**
1. Install the app
2. Open the app
3. `Connect to the network` screen opens
4. Connect to the network
5. Close the app
6. Open the app
7. See the `connect to the network` page opens again

**Expected behavior**
Instead of asking every time connect to the network take me to the login screen

**Actual behavior**
Asking to connect to the network every time app opens

**Screenshots/Recordings**
<img width="150" alt="Connect to the network" src="https://user-images.githubusercontent.com/22790904/128536662-3d5fe303-755c-4ed3-a5fb-c081081c1bd0.png">

**Comment by hussu010** [comment]
Could we have a list of the trusted banks in the list and the last tab will be `Add bank manually` so that the users won't need to find the bank address through discord or reddit or asking a friend.

**Comment by manishram** [comment]
Yes @hussu010, we are going to do that. In fact, we'll just auto-connect them to thenewboston's managed bank on their first installation. They can switch bank afterward.
Let me know what you think about this.

**Comment by manishram** [comment]
Fixed by: https://github.com/thenewboston-developers/thenewboston-mobile/commit/10b970c640b2f50bac3e4fc0064d227122eba183

**Comment by manishram** [comment]
@katolykdev the `Connect to the network` screen appears for half second when the app starts and then switches to the login page.

**Comment by katolykdev** [comment]
@manishram, @zinoadidi  Fixed it.
