### ISSUE TITLE
Ripple effect overflow the button

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Account-Manager-Mobile#22]
**Bug Description**
On clicking any button in the app, it gives a ripple effect that overflows out of the button.

**Screenshot:**

<img width="150" src="https://user-images.githubusercontent.com/22790904/128576743-5882f744-2f7a-45dc-b570-80ce34f5cb3c.png">

---

**Expected:**
The ripple effect stays inside the button

**Comment by katolykdev** [comment]
@manishram, @zinoadidi  Fixed it.
