### ISSUE TITLE
Build for iOS and Android

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Account-Manager-Mobile#33]
**Task:**
1. Check out this branch: https://github.com/thenewboston-developers/thenewboston-mobile/tree/sdk-integration
2. merge `development` into the branch 
3. Fix the app such that the app can be built for both android and iOS development. 
4. Update the README with instructions on how to build for both platforms

Acceptance Criteria:
- I should be able to follow the directions in README and successfully build the app in both iOS and Android emulator 

---
**Note:**
* [sdk-integration ](https://github.com/thenewboston-developers/thenewboston-mobile/tree/sdk-integration) branch got the most up to date codes.
* One can build for android from `sdk-integration` branch. Try to run: `gradlew clean` in `android` directory before building.

**Comment by wakawakathedev** [comment]
👋

**Comment by C41M50N** [comment]
Is vanilla React-Native a requirement or can Expo be used as well?

**Comment by manishram** [comment]
@Chuckinator2020 we are using vanilla react native.
